spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 6000
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
  datasource:
    druid:
      # 起始
      url: jdbc:mysql://localhost:3306/test2?useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      # 结束 这之间和spring.datasource.url ,spring.datasource.driver-class-name 等等是一样的
      initial-size: 1
      max-active: 10
      min-idle: 1
      validation-query: select 1
      test-while-idle: true
      time-between-eviction-runs-millis: 60000